apt_packages:
  - qemu-guest-agent
  - curl
  - wget
  - git
  - vim
  - tree
  - rsync
  - zip
  - unzip
  - ca-certificates
  - apt-transport-https
  - software-properties-common
  - build-essential
  - bash-completion
  - jq
  - socat
  - gnupg2
  - htop
  - iotop
  - iftop
  - iperf3
  - neofetch

docker_compose_version: "1.29.2"
docker_users:
  - ubuntu
