---

- name: Render the kubeadm init config template
  ansible.builtin.template:
    src: init-config.yml.j2
    dest: /tmp/config.yml

- name: kubeadm init
  ansible.builtin.shell: kubeadm init --config /tmp/config.yml | tee /tmp/kubeadm_init.log
  register: kubeadm_init

- name: kubeadm init (stdout)
  ansible.builtin.debug:
    var: kubeadm_init.stdout_lines

- name: kubeadm init (stderr)
  ansible.builtin.debug:
    var: kubeadm_init.stderr_lines