---
- name: Pull kube-vip image
  ansible.builtin.command: ctr image pull {{ kubevip_image }}:{{ kubevip_tag }}
  register: result
  changed_when: "'0.0 B' not in result.stdout"

- name: Ensure the kubernetes static manifests path exists
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: 0755

- ansible.builtin.include_tasks: static-pod.yml
  when: kubevip_cluster_type == 'kubeadm'

- ansible.builtin.include_tasks: daemonset.yml
  when: kubevip_cluster_type != 'kubeadm'

- ansible.builtin.include_tasks: cloud-controller.yml
  when: kubevip_services_enable == true
