---
- name: Install
  hosts: 127.0.0.1
  connection: local
  become: true

  vars_files:
    - ../vars/default.yml

  tasks:
    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: true
        cache_valid_time: 600
        install_recommends: false
        upgrade: dist
      retries: 3
      register: result
      until: result is succeeded

  roles:
    - geerlingguy.docker
