---
kubernetes_cni_plugin: calico  # See kubernetes_cni_plugin_list for a list of supported values
kubernetes_cni_plugin_cidr: 10.244.0.0/16  # This is the same cidr used for podSubnet in kubeadm InitConfiguration
